using Blazor.SubtleCrypto;
using Microsoft.JSInterop;

namespace WebApp.Services;

/// <summary>
/// Encrypts/decrypts the master password for storage in the browser's localStorage.
/// Uses Blazor.SubtleCrypto (backed by the browser's Web Crypto SubtleCrypto API and
/// AES-GCM) since System.Security.Cryptography.Aes is not supported on browser-wasm.
/// A fresh key/IV is generated by SubtleCrypto for every save and stored alongside the
/// ciphertext so it can be reused for decryption.
/// </summary>
public class MasterPasswordProtector
{
    private const string CiphertextStorageKey = "pwdgen.masterPassword";
    private const string EncryptionKeyStorageKey = "pwdgen.masterPasswordKey";

    private readonly ICryptoService _crypto;
    private readonly IJSRuntime _jsRuntime;

    public MasterPasswordProtector(ICryptoService crypto, IJSRuntime jsRuntime)
    {
        _crypto = crypto;
        _jsRuntime = jsRuntime;
    }

    public async Task SaveAsync(string plainTextMasterPassword)
    {
        var encrypted = await _crypto.EncryptAsync(plainTextMasterPassword);
        if (encrypted is null || !encrypted.Status || encrypted.Secret?.Key is null)
        {
            await ClearAsync();
            return;
        }

        await _jsRuntime.InvokeVoidAsync("localStorage.setItem", CiphertextStorageKey, encrypted.Value);
        await _jsRuntime.InvokeVoidAsync("localStorage.setItem", EncryptionKeyStorageKey, encrypted.Secret.Key);
    }

    public async Task<string?> LoadAsync()
    {
        var ciphertext = await _jsRuntime.InvokeAsync<string?>("localStorage.getItem", CiphertextStorageKey);
        var key = await _jsRuntime.InvokeAsync<string?>("localStorage.getItem", EncryptionKeyStorageKey);

        if (string.IsNullOrEmpty(ciphertext) || string.IsNullOrEmpty(key))
        {
            return null;
        }

        try
        {
            var decrypted = await _crypto.DecryptAsync(new CryptoInput { Value = ciphertext, Key = key });
            if (string.IsNullOrEmpty(decrypted))
            {
                await ClearAsync();
                return null;
            }

            return decrypted;
        }
        catch (Exception)
        {
            // Corrupted or tampered storage entry - treat as if nothing was saved.
            await ClearAsync();
            return null;
        }
    }

    public async Task ClearAsync()
    {
        await _jsRuntime.InvokeVoidAsync("localStorage.removeItem", CiphertextStorageKey);
        await _jsRuntime.InvokeVoidAsync("localStorage.removeItem", EncryptionKeyStorageKey);
    }
}
